import { Toaster } from "@/components/ui/toaster";
import NavigationBar from "@/components/sections/navigation";
import Footer from "@/components/sections/footer";

import { inter, ceraRoundPro } from "@/utils/fonts";
import "./globals.css";

export const metadata = {
  title: {
    template: "%s | Ralph Ortiz",
    default: "Ralph Ortiz",
  },
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter} ${ceraRoundPro}`}>
        <div className="grid min-h-[100dvh] grid-rows-[auto_1fr_auto]">
          <NavigationBar />
          <main>{children}</main>
          <Toaster />
          <Footer />
        </div>
      </body>
    </html>
  );
}
